usePodIdentity: "false"
keyvaultName: "{{KEYVAULT_NAME}}"
objects: |
  array:
    - |
      objectName: "{{OBJECT1_NAME}}"
      objectAlias: "{{OBJECT1_ALIAS}}"
      objectType: "{{OBJECT1_TYPE}}"
      objectVersion: "{{OBJECT1_VERSION}}"
    - |
      objectName: "{{OBJECT2_NAME}}"
      objectAlias: "{{OBJECT2_ALIAS}}"
      objectType: "{{OBJECT2_TYPE}}"
      objectVersion: "{{OBJECT2_VERSION}}"
    - |
      objectName: "{{CERT1_NAME}}"
      objectAlias: "{{CERT1_NAME}}-pub-key"
      objectType: "key"
      objectVersion: ""
    - |
      objectName: "{{CERT1_NAME}}"
      objectAlias: "{{CERT1_NAME}}"
      objectType: "cert"
      objectVersion: ""
    - |
      objectName: "{{CERT1_NAME}}"
      objectAlias: "{{CERT1_NAME}}-secret"
      objectType: "secret"
      objectVersion: ""
    - |
      objectName: "{{CERT2_NAME}}"
      objectAlias: "{{CERT2_NAME}}-pub-key"
      objectType: "key"
      objectVersion: ""
    - |
      objectName: "{{CERT2_NAME}}"
      objectAlias: "{{CERT2_NAME}}"
      objectType: "cert"
      objectVersion: ""
    - |
      objectName: "{{CERT2_NAME}}"
      objectAlias: "{{CERT2_NAME}}-secret"
      objectType: "secret"
      objectVersion: ""
    - |
      objectName: "{{CERT3_NAME}}"
      objectAlias: "{{CERT3_NAME}}-pub-key"
      objectType: "key"
      objectVersion: ""
    - |
      objectName: "{{CERT3_NAME}}"
      objectAlias: "{{CERT3_NAME}}"
      objectType: "cert"
      objectVersion: ""
    - |
      objectName: "{{CERT3_NAME}}"
      objectAlias: "{{CERT3_NAME}}-secret"
      objectType: "secret"
      objectVersion: ""
tenantId: "{{TENANT_ID}}"
