usePodIdentity: "false"
keyvaultName: "{{KEYVAULT_NAME}}"
objects:  |
  array:
    - |
      objectName: databasePassword
      objectType: secret
    - |
      objectName: storageToken
      objectType: secret
tenantId: "{{TENANT_ID}}"
