usePodIdentity: "false"
keyvaultName: "{{KEYVAULT_NAME}}"
objects:  |
  array:
    - |
      objectName: databasePassword
      objectType: secret
    - |
      objectName: storageToken
      objectType: secret
resourceGroup: "{{KEYVAULT_RESOURCE_GROUP}}"
subscriptionId: "{{AZURE_SUBSCRIPTION_ID}}"
tenantId: "{{AZURE_TENANT_ID}}"
