run:
  timeout: 5m
  skip-dirs: []
  skip-files: []

linters:
  disable-all: true
  enable:
    - deadcode
    - errorlint
    - gofmt
    - goimports
    - gosimple
    - revive
    - govet
    - gosec
    - ineffassign
    - misspell
    - unused
    - structcheck
    - varcheck
