run:
  timeout: 5m
  skip-dirs: []
  skip-files: []

linters:
  disable-all: true
  enable:
    - deadcode
    - errorlint
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unused
    - structcheck
    - varcheck
    - revive
