{{- if .Values.arc.isMonitoringEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sscdpa.arc.fullname" . }}-telegraf-config
  namespace: {{ .Release.Namespace }}
data:
  telegraf.conf: |
{{ (tpl ( .Files.Get "config/telegraf-conf.tmpl") .) | indent 4 }}
---
apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: {{ template "sscdpa.arc.fullname" . }}-mdm-config
  namespace: {{ .Release.Namespace }}
data: 
  mdmconfig.json: "{\"imdsInfo\":[{ \"account\": \"{{ .Values.arc.metrics.mdm.accountName }}\" }]}"
{{- end }}
