{{- if .Values.enableArcExtension }}
{{- if .Values.arc.enableMonitoring }}
apiVersion: v1
kind: Service
metadata:
  name: arc-geneva-logging-service
  namespace: {{ .Release.Namespace }}
{{ include "sscdpa.arc.labels" . | indent 2 }}
spec:
  type: ClusterIP
  ports:
    - name: mds-fluentd-tcp
      protocol: TCP
      port: 8130
      targetPort: 8130
  selector:
    app: "arc-monitoring"
{{- end }}
{{- end }}
