{{- if .Values.Azure.Identity.isEnabled }}
apiVersion: clusterconfig.azure.com/v1beta1
kind: AzureExtensionIdentity
metadata:
  name: {{ template "sscdpa.fullname" . }}-arc-ext-identity
  namespace: azure-arc
spec:
  serviceAccounts:
    - name: csi-secrets-store-provider-azure
      namespace: {{ .Release.Namespace }}
  tokenNamespace: {{ .Release.Namespace }}
{{- end }}
