{{ if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-secrets-store-provider-azure
  namespace: {{ .Release.Namespace }}
{{ include "sscdpa.labels" . | indent 2 }}
{{ end }}
