{{ if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-secrets-store-provider-azure
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sscdpa.labels" . | nindent 4 }}
{{ end }}
