apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-docker-config
spec:
  provider: azure
  secretObjects:                                # secretObjects defines the desired state of synced K8s secret objects
    - secretName: dockerconfig
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: dockerconfigjson
          key: .dockerconfigjson
  parameters:
    usePodIdentity: "false"
    keyvaultName: "kvname"                      # the name of the Keyvault
    objects: |
      array:
        - |
          objectName: dockerconfigjson
          objectType: secret                    # Setting the objectType to secret will retrieve the certificate and private key from keyvault.
    tenantId: "tid"                             # the tenant ID of the KeyVault
