apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-secrets-store-provider-azure
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: csi-secrets-store-provider-azure
  name: csi-secrets-store-provider-azure-windows
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: csi-secrets-store-provider-azure
  template:
    metadata:
      labels:
        app: csi-secrets-store-provider-azure
    spec:
      serviceAccountName: csi-secrets-store-provider-azure
      containers:
        - name: provider-azure-installer
          image: mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.9
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=unix://C:\\provider\\azure.sock
          lifecycle:
            preStop:
              exec:
                command:
                  [
                    "cmd",
                    "/c",
                    "del /f C:\\provider\\azure.sock",
                  ]
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - mountPath: "C:\\provider"
              name: providervol
            - name: mountpoint-dir
              mountPath: "C:\\var\\lib\\kubelet\\pods"
              mountPropagation: HostToContainer
      volumes:
        - name: providervol
          hostPath:
            path: "C:\\k\\secrets-store-csi-providers"
            type: DirectoryOrCreate
        - name: mountpoint-dir
          hostPath:
            path: C:\var\lib\kubelet\pods\
      nodeSelector:
        kubernetes.io/os: windows
