#this example for splitting the cert that has cert-bundle (cert, intermediate and root cert) 
# and in pfx format at azure kv certs
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-test
  namespace: default
spec:
  parameters:
    clientID: <myclientid>
    keyvaultName: mykv
    objects: |
      array:
        - |
          objectName: "mycert_in_pem"
          objectType: secret
          objectAlias: appcert
          objectFormat: pem
    tenantId: <tenant-id>
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
  provider: azure
  secretObjects:    #split cert-bundle as cert and key as key from secret type of object
    - data:
        - key: cert
          objectName: appcert.crt
        - key: key
          objectName: appcert.key
      secretName: my-csi-driver-sync-secret
      type: Opaque
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: <azure-client-id>
  name: nginx-sync-as-secret
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-sync-as-secret
  name: nginx-sync-as-secret
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: nginx-sync-as-secret
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: anginx-sync-as-secret
    spec:
      serviceAccountName: nginx-sync-as-secret
      containers:
          image: nginx
          imagePullPolicy: Always
          name: nginx-sync-as-secret
          volumeMounts:
            - mountPath: /secrets
              name: all-secrets
              readOnly: true
      volumes:
        - csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kv-test
          name: all-secrets
