apiVersion: v1
entries:
  csi-secrets-store-provider-azure:
  - apiVersion: v1
    appVersion: 0.0.5
    created: "2020-04-29T12:35:37.793794-07:00"
    dependencies:
    - condition: driver.install
      name: secrets-store-csi-driver
      repository: https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts
      version: 0.0.9
    description: A Helm chart to install the Secrets Store CSI Driver and the Azure
      Keyvault Provider inside a Kubernetes cluster.
    digest: b1b4cfe79c87fd2139e5ee498040d78678ac480940c00b245711edbe6516451e
    home: https://github.com/Azure/secrets-store-csi-driver-provider-azure
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: Anish Ramasekar
    name: csi-secrets-store-provider-azure
    sources:
    - https://github.com/Azure/secrets-store-csi-driver-provider-azure
    urls:
    - https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts/csi-secrets-store-provider-azure-0.0.5.tgz
    version: 0.0.5
generated: "2020-04-29T12:35:37.790031-07:00"
