jobs:
  - job:
    variables:
    - group: csi-secrets-store-e2e
    steps:
    - script: |
        az login -i > /dev/null
        az account set -s=$(SUBSCRIPTION_ID)
      displayName: "az login"
    - script: |
        az extension add --name connectedk8s
        az extension add --name k8s-extension
      displayName: "add cli extensions"
    - script: |
        az extension add --name connectedk8s
        az extension add --name k8s-extension
      displayName: "add cli extensions"
    - script: |
        make install-kubectl setup-kind
      displayName: "setup KinD"
    - script: |
        echo "##vso[task.setvariable variable=AZURE_CLUSTER_NAME]sscd-arc-e2e-$(openssl rand -hex 6)"
        echo ${AZURE_CLUSTER_NAME}
      displayName: "Set cluster name"
      condition: succeeded()
    - script: |
        az group create -n ${AZURE_CLUSTER_NAME} -l $(AZURE_LOCATION)

        az connectedk8s connect -n ${AZURE_CLUSTER_NAME} -g ${AZURE_CLUSTER_NAME}
      displayName: "connect KinD cluster"
      condition: succeeded()
    - template: teardown.yaml