jobs:
  - job:
    timeoutInMinutes: 20
    cancelTimeoutInMinutes: 5
    dependsOn:
    - lint
    - scan_images
    - unit_test
    - build
    workspace:
      clean: all
    variables:
    - group: csi-secrets-store-e2e-kind
    strategy:
      matrix:
        kind_v1_23_13_helm:
          KIND_K8S_VERSION: v1.23.13
          IS_HELM_TEST: true
        kind_v1_24_7_helm:
          KIND_K8S_VERSION: v1.24.7
          IS_HELM_TEST: true
        kind_v1_25_3_helm:
          KIND_K8S_VERSION: v1.25.3
          IS_HELM_TEST: true
        kind_v1_26_0_helm:
          KIND_K8S_VERSION: v1.26.0
          IS_HELM_TEST: true
        kind_v1_23_13_deployment_manifest:
          KIND_K8S_VERSION: v1.23.13
          IS_HELM_TEST: false
        kind_v1_24_7_deployment_manifest:
          KIND_K8S_VERSION: v1.24.7
          IS_HELM_TEST: false
        kind_v1_25_3_deployment_manifest:
          KIND_K8S_VERSION: v1.25.3
          IS_HELM_TEST: false
        kind_v1_26_0_deployment_manifest:
          KIND_K8S_VERSION: v1.26.0
          IS_HELM_TEST: false

    steps:
      # logging in to download the sa.pub and sa.key used for creating the kind cluster
      # with OIDC issuer enabled
      - template: az-login.yaml
      - script: |
          export REGISTRY="e2e"
          export IMAGE_VERSION=e2e-$(git rev-parse --short HEAD)
          echo "Image version: ${IMAGE_VERSION}"
          echo "##vso[task.setvariable variable=IMAGE_VERSION]${IMAGE_VERSION}"
          echo "##vso[task.setvariable variable=REGISTRY]${REGISTRY}"
          make e2e-bootstrap
        displayName: "Build image"
        env:
          CI_KIND_CLUSTER: true
          SERVICE_ACCOUNT_ISSUER: $(SERVICE_ACCOUNT_ISSUER)
          SERVICE_ACCOUNT_KEYVAULT_NAME: $(SERVICE_ACCOUNT_KEYVAULT_NAME)
      - script: |
          make e2e-test
        displayName: Run e2e tests
        env:
          AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
          AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
          KEY_NAME: $(KEY_NAME)
          KEY_VERSION: $(KEY_VERSION)
          KEYVAULT_NAME: $(KEYVAULT_NAME)
          SECRET_NAME: $(SECRET_NAME)
          TENANT_ID: $(TENANT_ID)
          CI_KIND_CLUSTER: true
          AZURE_ENVIRONMENT_FILEPATH: "/etc/kubernetes/custom_environment.json"

      - script: |
          make e2e-kind-cleanup
        displayName: Delete kind cluster
        condition: always()
