jobs:
  - job: setup_az_cli
    variables:
    - group: csi-secrets-store-e2e
    steps:
    - script: |
        az login -i > /dev/null
        az account set -s=$(SUBSCRIPTION_ID)
        displayName: "az login"