jobs:
  - job: lint
    timeoutInMinutes: 5
    workspace:
      clean: all
    steps:
      - task: GoTool@0
        inputs:
          version: '1.24.7'
      - script: make lint
        displayName: golangci-lint
      - script: make helm-lint
        displayName: helm lint
      - script: make shellcheck
        displayName: shellcheck
  - job: build
    timeoutInMinutes: 5
    workspace:
      clean: all
    steps:
      - task: GoTool@0
        inputs:
          version: '1.24.7'
      - script: make build build-windows
        displayName: build
  - job: unit_test
    timeoutInMinutes: 5
    workspace:
      clean: all
    steps:
      - task: GoTool@0
        inputs:
          version: '1.24.7'
      - script: make unit-test
        displayName: unit test
