jobs:
- job: unit_test
  timeoutInMinutes: 10
  cancelTimeoutInMinutes: 5
  workspace:
    clean: all
  steps:
    - task: GoTool@0
      inputs:
        version: 1.16
    - script: make lint
      displayName: Run lint
    - script: make build build-windows
      displayName: Build
    - script: make unit-test
      displayName: Run unit tests
    - script: bash <(curl -s https://codecov.io/bash) -C $(Build.SourceVersion)
      displayName: Upload coverage to codecov
    - script: make helm-lint
      displayName: Run helm lint
    - template: scan-images.yaml
