apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-keys
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: "kvname"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: key1
          objectType: key                       # object types: secret, key or cert
          objectVersion: ""                     # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: key2
          objectType: key
          objectVersion: ""
          objectAlias: "KEY_ALIAS"              # [OPTIONAL] specify the filename of the object when written to disk. Defaults to objectName if not provided.
    tenantId: "tid"
