# This is a sample pod definition for using SecretProviderClass and aad-pod-identity for authentication with Key Vault
kind: Pod
apiVersion: v1
metadata:
  name: nginx-secrets-store-inline-podid
  labels:
    aadpodidbinding: "demo"
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kvname-podid"
