kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-secrets-store-deployment
  labels:
    app: nginx-secrets-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-secrets-store
  template:
    metadata:
      labels:
        app: nginx-secrets-store
    spec:
      containers:
      - image: nginx
        name: nginx-secrets-store
        volumeMounts:
        - name: secrets-store01
          mountPath: "/mnt/secrets-store" 
          readOnly: true
      volumes:
      - name: secrets-store01
        persistentVolumeClaim:
          claimName: pvc-secrets-store
          readOnly: true
