{{- if .Values.rbac.pspEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "sscdpa.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sscdpa.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "sscdpa.psp.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: csi-secrets-store-provider-azure
    namespace: {{ .Release.Namespace }}
{{- end }}
