apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: "kvname"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: secret1
          objectType: secret                    # object types: secret, key or cert
          objectVersion: ""                     # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: secret2
          objectType: secret
          objectVersion: ""
          objectAlias: "SECRET_ALIAS"           # [OPTIONAL] specify the filename of the object when written to disk. Defaults to objectName if not provided.
        - |
          objectName: secret3
          objectType: secret
          objectVersion: ""
          objectEncoding: "SECRET_ALIAS"        # [OPTIONAL] the encoding of the Azure Key Vault secret object. Supported types are utf-8, hex and base64. This option is supported only with objectType: secret. Default encoding is utf-8.
    tenantId: "tid"
