trigger: none

schedules:
  - cron: "0 0 * * *"
    always: true
    displayName: "Nightly Build & Test"
    branches:
      include:
        - master

pool:
  vmImage: ubuntu-latest

jobs:
  - template: templates/load-test.yaml
  - template: templates/e2e-test-azure.yaml
    parameters:
      clusterTypes:
      - "aks"
      - "aks-engine"
      osTypes:
      - "linux"
      - "windows"
      testClusterUpgrade: true
  - template: templates/soak-test.yaml
    parameters:
      clusterConfigs:
      - "csi-secrets-store-soak-linux-aks"
      - "csi-secrets-store-soak-win-aks"
