trigger: none

schedules:
  - cron: "0 0 * * *"
    always: true
    displayName: "Nightly Build & Test"
    branches:
      include:
        - master

pool: staging-pool

jobs:
  # to get image scan results on nightly runs
  - template: templates/unit-test.yaml
  - template: templates/e2e-test-kind.yaml
    parameters:
      driverWriteSecrets:
      - "true"
      - "false"
  - template: templates/load-test.yaml
  - template: templates/e2e-test-azure.yaml
    parameters:
      clusterTypes:
      - "aks"
      - "aks-engine"
      osTypes:
      - "linux"
      - "windows"
      testClusterUpgrade: true
  - template: templates/e2e-test-azure.yaml 
    parameters:
      clusterTypes:
      - "aks"
      osTypes:
      - "linux"
      testWithGPU: true
  - template: templates/soak-test.yaml
    parameters:
      clusterConfigs:
      - "csi-secrets-store-soak-linux-aks"
      - "csi-secrets-store-soak-win-aks"
  - template: templates/arc/e2e-test-kind.yaml
  - template: templates/arc/e2e-test-aks.yaml
