trigger: none

schedules:
  - cron: "0 0 * * *"
    always: true
    displayName: "Nightly Build & Test"
    branches:
      include:
        - master

pool:
  vmImage: ubuntu-latest

jobs:
  - template: load-tests-template.yaml
  - template: e2e-tests-template.yaml
    parameters:
      clusterTypes:
      - "aks"
      - "aks-engine"
      osTypes:
      - "linux"
      - "windows"
  - template: soak-tests-template.yaml
    parameters:
      clusterConfigs:
      - "csi-secrets-store-soak-linux-aks"
      - "csi-secrets-store-soak-win-aks"
