jobs:
  - job: e2e_arc_test
    variables:
    - name: AZURE_ENVIRONMENT_FILEPATH
      value: /etc/kubernetes/custom_environment.json
    - name: VOLUME_NAME
      value: cloudenvfile-vol
    - group: csi-secrets-store-e2e
    steps:
      - template: ../build-images.yaml
        parameters:
          registry: e2e
          ciKindCluster: true
      - template: arc-setup.yaml
      - script: |
          buildNumber="$(echo $(Build.BuildNumber) | tr -d '.')"
          version="0.0.$buildNumber"
          version="0.0.99"
          echo "##vso[task.setvariable variable=EXT_VERSION]$version"

          # helm dependency update manifest_staging/charts/csi-secrets-store-provider-azure
          # helm package manifest_staging/charts/csi-secrets-store-provider-azure --version $version

          # echo "Authenticating..."
          # az acr login -n $(STAGING_REGISTRY_NAME)

          # echo 'Pushing chart...'
          # oras push $(STAGING_REGISTRY):$version ./csi-secrets-store-provider-azure-$version.tgz:application/tar+gzip --debug
        displayName: 'Push OCI helm chart to ACR'
        condition: succeeded()
      - template: arc-connect.yaml
      - template: arc-extension-create.yaml
        parameters:
          azureClusterName: $(AZURE_CLUSTER_NAME)
          extensionVersion: $(EXT_VERSION)
          releaseTrain: dev
          configurationSettings: "'secrets-store-csi-driver.enableSecretRotation=true' \
          'secrets-store-csi-driver.rotationPollInterval=30s' \
          'linux.image.tag=$(IMAGE_VERSION)' \
          'linux.image.repository=$(REGISTRY)/provider-azure' \
          'secrets-store-csi-driver.syncSecret.enabled=true' \
          'linux.volumes[0].name=$(VOLUME_NAME)' \
          'linux.volumes[0].hostPath.path=$(AZURE_ENVIRONMENT_FILEPATH)' \
          'linux.volumes[0].hostPath.type=File' \
          'linux.volumeMounts[0].name=$(VOLUME_NAME)' \
          'linux.volumeMounts[0].mountPath=$(AZURE_ENVIRONMENT_FILEPATH)'"
      - template: ../e2e-test.yaml
        parameters:
          testName: "arc extension e2e test"
          ciKindCluster: true
          isArcTest: true
      - script: |
          kubectl get ec -A -o yaml
        displayName: "test ec"
        condition: always()
      - script: |
          az account set -s=$(SUBSCRIPTION_ID)
          az acr login -n $(STAGING_REGISTRY_NAME)
          registry=$(STAGING_REGISTRY)
          respository=${registry#*/}
          echo "deleting - $respository:$(EXT_VERSION)"
          az acr repository delete --name $(STAGING_REGISTRY_NAME) -t $respository:$(EXT_VERSION) -y || true
        displayName: "delete e2e OCI helm chart"
        condition: always()
      - template: ../teardown.yaml
