jobs:
  - job: e2e_arc_test
    variables:
    - name: AZURE_ENVIRONMENT_FILEPATH
      value: /etc/kubernetes/custom_environment.json
    - name: VOLUME_NAME
      value: cloudenvfile-vol
    - group: csi-secrets-store-e2e
    steps:
      - template: ../build-images.yaml
        parameters:
          registry: e2e
          ciKindCluster: true
      - template: setup.yaml
      - script: |
          buildNumber="$(echo $(Build.BuildNumber) | tr -d '.')"
          version="0.0.$buildNumber"
          echo "##vso[task.setvariable variable=EXT_VERSION]$version"

          helm dependency update manifest_staging/charts/csi-secrets-store-provider-azure
          helm package manifest_staging/charts/csi-secrets-store-provider-azure --version $version

          # echo "Authenticating..."
          az acr login -n $(STAGING_REGISTRY_NAME)

          # echo 'Pushing chart...'
          oras push $(STAGING_REGISTRY):$version ./csi-secrets-store-provider-azure-$version.tgz:application/tar+gzip --debug

          registry=$(STAGING_REGISTRY)
          respository=${registry#*/}
          echo "##vso[task.setvariable variable=REGISTRY_REPO]$respository"
        displayName: 'Push OCI helm chart to ACR'
        condition: succeeded()
      - template: cluster-connect.yaml
      - template: extension-create.yaml
        parameters:
          azureClusterName: $(AZURE_CLUSTER_NAME)
          extensionVersion: $(EXT_VERSION)
          releaseTrain: dev
          configurationSettings: "'secrets-store-csi-driver.enableSecretRotation=true' \
          'secrets-store-csi-driver.rotationPollInterval=30s' \
          'linux.image.tag=$(IMAGE_VERSION)' \
          'linux.image.repository=$(REGISTRY)/provider-azure' \
          'secrets-store-csi-driver.syncSecret.enabled=true' \
          'linux.volumes[0].name=$(VOLUME_NAME)' \
          'linux.volumes[0].hostPath.path=$(AZURE_ENVIRONMENT_FILEPATH)' \
          'linux.volumes[0].hostPath.type=File' \
          'linux.volumeMounts[0].name=$(VOLUME_NAME)' \
          'linux.volumeMounts[0].mountPath=$(AZURE_ENVIRONMENT_FILEPATH)'"
      - template: ../e2e-test.yaml
        parameters:
          testName: "arc extension e2e test"
          ciKindCluster: true
          isArcTest: true
      - template: ../teardown.yaml
      - template: ../cleanup-images.yaml
        parameters:
          imageVersion: $(EXT_VERSION)
          registryRepo: $(REGISTRY_REPO)
          subscriptionId: $(SUBSCRIPTION_ID)
          registryName: $(STAGING_REGISTRY_NAME)
          isMultiArch: false
