jobs:
  - job: e2e_arc_kind
    variables:
    - name: AZURE_ENVIRONMENT_FILEPATH
      value: /etc/kubernetes/custom_environment.json
    - name: VOLUME_NAME
      value: cloudenvfile-vol
    - group: csi-secrets-store-e2e-kind
    steps:
    - template: ../az-login.yaml
    - template: setup.yaml
    - script: |
        make install-helm install-kubectl setup-kind
      displayName: "install dependencies and setup kind"
      condition: succeeded()
      env:
        SERVICE_ACCOUNT_ISSUER: $(SERVICE_ACCOUNT_ISSUER)
        SERVICE_ACCOUNT_KEYVAULT_NAME: $(SERVICE_ACCOUNT_KEYVAULT_NAME)
    - template: cluster-connect.yaml
    - template: extension-create.yaml
      parameters:
        azureClusterName: $(AZURE_CLUSTER_NAME)
        releaseTrain: preview
        configurationSettings: "'secrets-store-csi-driver.enableSecretRotation=true' \
        'secrets-store-csi-driver.rotationPollInterval=30s' \
        'secrets-store-csi-driver.syncSecret.enabled=true' \
        'linux.volumes[0].name=$(VOLUME_NAME)' \
        'linux.volumes[0].hostPath.path=$(AZURE_ENVIRONMENT_FILEPATH)' \
        'linux.volumes[0].hostPath.type=File' \
        'linux.volumeMounts[0].name=$(VOLUME_NAME)' \
        'linux.volumeMounts[0].mountPath=$(AZURE_ENVIRONMENT_FILEPATH)'"
    - template: ../e2e-test.yaml
      parameters:
        testName: "arc extension e2e test"
        ciKindCluster: true
        isArcTest: true
    - template: ../teardown.yaml
